/*
 * Ini adalah simulasi program MP3 & WAV Player, sebagai salah satu
 * pengumpulan tugas UTS mata kuliah Algoritma & Pemrograman 2
 */
package uts_ke2;

import java.io.File;
import java.io.IOException;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * Nama         : Septian Moh.Ridwan
 * NIM          : 1855201034
 * Prodi/Kelas  : Ilmu Komputer semester 4
 * @author Septian_MR :P
 */
public class MyPlayere extends javax.swing.JFrame {

    mainclass Mp3Klas = new mainclass();
    mainclass2 WavKlas = new mainclass2();
    public static int count;
    
   
    public MyPlayere() throws UnsupportedAudioFileException, IOException, LineUnavailableException {
        initComponents();
        this.setTitle("MyPlayere");
        this.setLocationRelativeTo(this);
        Mulai.setEnabled(false);
        Jeda.setEnabled(false);
        Mati.setEnabled(false);
        Ulang.setEnabled(false);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        Mulai = new javax.swing.JButton();
        Jeda = new javax.swing.JButton();
        Mati = new javax.swing.JButton();
        Pilih = new javax.swing.JButton();
        Ulang = new javax.swing.JButton();
        Path = new javax.swing.JLabel();
        Pinta = new javax.swing.JLabel();
        retry = new javax.swing.JLabel();
        Pilih2 = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Mulai.setText("|>");
        Mulai.setToolTipText("Mulai jalankan lagunya!");
        Mulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MulaiActionPerformed(evt);
            }
        });

        Jeda.setText("||");
        Jeda.setToolTipText("Tunda lagunya sejenak");
        Jeda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JedaActionPerformed(evt);
            }
        });

        Mati.setText("[ ]");
        Mati.setToolTipText("Matikan lagunya");
        Mati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatiActionPerformed(evt);
            }
        });

        Pilih.setText("Pilih MP3");
        Pilih.setToolTipText("Pilih lagu yang ingin diputar");
        Pilih.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihActionPerformed(evt);
            }
        });

        Ulang.setText("∞");
        Ulang.setToolTipText("Pilih untuk memutar ulang lagu secara otomatis");
        Ulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UlangActionPerformed(evt);
            }
        });

        Path.setBackground(new java.awt.Color(255, 255, 255));
        Path.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        Path.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Path.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Pinta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pinta.setText("Ikuti : Pilih lagu yang akan diputar!");

        retry.setText("Ulangi : Tidak");

        Pilih2.setText("Pilih WAV");
        Pilih2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pilih2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pinta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Path, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ulang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(retry, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Jeda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Mulai)
                        .addGap(14, 14, 14)
                        .addComponent(Mati)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(Pilih)
                .addGap(102, 102, 102)
                .addComponent(Pilih2)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pilih)
                    .addComponent(Pilih2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Pinta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Path, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mulai)
                    .addComponent(Jeda)
                    .addComponent(Mati)
                    .addComponent(Ulang)
                    .addComponent(retry))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihActionPerformed
        FileFilter filter = new FileNameExtensionFilter("MP3 Files", "mp3");
        
        JFileChooser chooser = new JFileChooser("C:\\Music");
        chooser.addChoosableFileFilter(filter);
        
        int returnVal = chooser.showOpenDialog(null);
        
        if(returnVal == JFileChooser.APPROVE_OPTION){
            Mp3Klas.Stop();
            File myFile = chooser.getSelectedFile();
            String song = myFile + "";
            
            String name = chooser.getSelectedFile().getName();
            Path.setText(name);
            Path.setEnabled(true);
            
            try {
                Mp3Klas.Play(song);
            } catch (UnsupportedAudioFileException | LineUnavailableException ex) {
                JOptionPane.showMessageDialog(null, "File tidak bisa dibuka!");
            }
            Pinta.setText("Lagu sedang diputar...");
            Mulai.setEnabled(false);
            Jeda.setEnabled(true);
            Mati.setEnabled(true);
            Ulang.setEnabled(true);
            Pilih.setEnabled(false);
            Pilih2.setEnabled(false);
        }
    }//GEN-LAST:event_PilihActionPerformed

    private void MulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MulaiActionPerformed
        Mp3Klas.Resume();
        Pinta.setText("Lagu sedang diputar...");
        Mulai.setEnabled(false);
        Jeda.setEnabled(true);
        Mati.setEnabled(true);
        Ulang.setEnabled(true);
        Pilih.setEnabled(false);
        Pilih2.setEnabled(false);
    }//GEN-LAST:event_MulaiActionPerformed

    private void MatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatiActionPerformed
        Mp3Klas.Stop();
        Path.setText("");
        Pinta.setText("Mati. Pilih lagu yang akan diputar!");
        Mulai.setEnabled(false);
        Jeda.setEnabled(false);
        Ulang.setEnabled(false);
        Pilih.setEnabled(true);
        Pilih2.setEnabled(true);
        
        try {
            WavKlas.Stop();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            JOptionPane.showMessageDialog(null, "Maaf ada kesalahan. Coba lagi.");
        }
    }//GEN-LAST:event_MatiActionPerformed

    private void JedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JedaActionPerformed
        try {
            // TODO add your handling code here:
            Mp3Klas.Pause();
            Pinta.setText("...Jeda sebentar");
            Mulai.setEnabled(true);
            Jeda.setEnabled(false);
            Mati.setEnabled(false);
            Pilih.setEnabled(false);
            Pilih2.setEnabled(false);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Maaf ada kesalahan. Coba lagi.");
        }
    }//GEN-LAST:event_JedaActionPerformed

    private void UlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UlangActionPerformed
        switch(count){
            case 0:
                count = 1;
                retry.setText("Ulangi : Ya");
                break;
                
            case 1:
                count = 0;
                retry.setText("Ulangi : Tidak");
                break;
            
        }
    }//GEN-LAST:event_UlangActionPerformed

    private void Pilih2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pilih2ActionPerformed
        FileFilter filter = new FileNameExtensionFilter("WAV Files", "wav");
        
        JFileChooser chooser = new JFileChooser("C:\\Music");
        chooser.addChoosableFileFilter(filter);
        
        int returnVal = chooser.showOpenDialog(null);
        
        if(returnVal == JFileChooser.APPROVE_OPTION){
            File myFile = chooser.getSelectedFile();
            String song = myFile + "";
            
            String name = chooser.getSelectedFile().getName();
            Path.setText(name);
            Path.setEnabled(true);
            
            try {
                WavKlas.Play(song);
            } catch (UnsupportedAudioFileException | LineUnavailableException | IOException ex) {
                JOptionPane.showMessageDialog(null, "File tidak bisa dibuka!");
            }
            Pinta.setText("Lagu sedang diputar...");
            Mulai.setEnabled(false);
            Jeda.setEnabled(false);
            Mati.setEnabled(true);
            Ulang.setEnabled(false);
            retry.setText("Auto");
            Pilih.setEnabled(false);
            Pilih2.setEnabled(false);
        }
    }//GEN-LAST:event_Pilih2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyPlayere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyPlayere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyPlayere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyPlayere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MyPlayere().setVisible(true);
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
                    JOptionPane.showMessageDialog(null, "Maaf ada kesalahan. Coba lagi.");
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jeda;
    private javax.swing.JButton Mati;
    private javax.swing.JButton Mulai;
    private javax.swing.JLabel Path;
    private javax.swing.JButton Pilih;
    private javax.swing.JButton Pilih2;
    private javax.swing.JLabel Pinta;
    private javax.swing.JButton Ulang;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel retry;
    // End of variables declaration//GEN-END:variables
}
